spring:
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: Hello World (Dev)

---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: Hello World (Prod)
